version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5433'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: xyz:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8082:8082
    environment:
      - DB_URL=jdbc:postgresql://db:5433/postgres
    links:
      - db
volumes:
  db:
    driver: local