server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      order_inserts: true
      ddl-auto: update
      generate_statistics: true
      jdbc:
        batch_size: 4

ingestor:
  url: https://assignment.free.beeceptor.com/listings